### ISSUE TITLE
Permission for PhoneFacade

### ISSUE THREAD

**Issue by jkennethcarino** [qpython-mobile/qpython.org#12]
[PhoneFacade](http://www.mithril.com.au/android/doc/PhoneFacade.html) needs `READ_PHONE_STATE` permission to get it work.

![2014_07_12_10 19 06](https://cloud.githubusercontent.com/assets/6307355/3560427/45ca5170-096c-11e4-9657-1e06535f1edc.png)
and (an issue) when I get back to QEdit, the script needs to save again.
![2014_07_12_10 21 36](https://cloud.githubusercontent.com/assets/6307355/3560426/45c3128e-096c-11e4-9110-e163bdd65093.png)

Here's my `qpyplus_last_err.log`:

```
FINGERPRINT=samsung/GT-S5360/GT-S5360:2.3.6/GINGERBREAD/DXMJ1:user/release-keys
HARDWARE=bcm21553
UNKNOWN=unknown
RADIO=unknown
BOARD=totoro
PRODUCT=GT-S5360
DISPLAY=GINGERBREAD.DXMJ1
USER=dpi
HOST=DELL223
DEVICE=GT-S5360
TAGS=release-keys
MODEL=GT-S5360
BOOTLOADER=unknown
CPU_ABI=armeabi
CPU_ABI2=unknown
ID=GINGERBREAD
SERIAL=unknown
MANUFACTURER=samsung
BRAND=samsung
TYPE=user
android.app.RemoteServiceException: Bad notification posted from package com.hipipal.qpyplus: Coulding create icon: StatusBarIcon(pkg=com.hipipal.qpyplus id=0xffffffff level=0 visible=true num=0 )
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1048)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:130)
    at android.app.ActivityThread.main(ActivityThread.java:3687)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:507)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
    at dalvik.system.NativeStart.main(Native Method)
```

Thanks. :)

**Comment by falcolumbarius** [comment]
Is it possible to add read and write permissions for both contacts and user dictionary?
