### ISSUE TITLE
Beautiful Soup 4 import error

### ISSUE THREAD

**Issue by Puzomor** [qpython-mobile/qpython.org#186]
I have installed beautifulsoup4 package on python 3.2 using
`import pip`
`pip.main(['install', '-U', 'beautifulsoup4'])`

and it seems to have completed successfully, but when I try to import it, I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.2/site-packages/bs4/__init__.py", line 53
    'You are trying to run the Python 2 version of Beautiful Soup under Python 3. This will not work.'<>'You need to convert the code, either by installing it (python setup.py install) or by running 2to3 (2to3 -w bs4).'
```

What do I do to make it work?

**Comment by robinchatterjee** [comment]
open the pip console and install using pip install bautifulsoup4....

After that import bs4
