### ISSUE TITLE
Cannot run scripts or open python console

### ISSUE THREAD

**Issue by tzzt** [qpython-mobile/qpython.org#22]
Hi,
if I want to run a script or console from menu qpython only opens the android terminal emulator.
The problem exists in qpython and qpython3.
I am using Android 4.4.4 and CyanogenMod 11.

Best regards

**Comment by vinniec** [comment]
I have the same problem!

**Comment by jtpio** [comment]
Same problem on my Nexus 7 (running CyanogenMod 11) but it works fine on a Nexus 5.

So it is basically the same error as what is described above.
It shows a prompt when running a script, which in my case is:
u0_a111@grouper:/ $

**Comment by riverfor** [comment]
Which version are you using ?

On Sun, Apr 19, 2015 at 9:25 PM, Jeremy Tuloup <notifications@github.com>
wrote:

> Same problem on my Nexus 7 (running CyanogenMod 11) but it works fine on a
> Nexus 5.
>
> So it is basically the same error as what is described above.
> It shows a prompt when running a script, which in my case is:
> u0_a111@grouper:/ $
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/qpython-android/qpython.org/issues/22#issuecomment-94276647>
> .
>



-- 
river's showtime, river's game

**Comment by jtpio** [comment]
QPython3, version 0.9.4 (2015/1/26) according to Google Play.

**Comment by ldoktor** [comment]
Hello guys, I just installed qpython-1.0.6 beta and I have the same problem. When I run Console, this occurs:

```
/data/data/com.hipipal.qpyplus/files/bin/qpython.sh && exit
u0_a163@crespo:/ $
```

and that's it. I'm in shell. When I copy & paste the command and press enter, interactive console executes, after exit it quits back to qpython main screen.

The same happens when I run scripts (hello world runs when I re-run the command manually). Projects, on the other hand, works fine.

I have no idea about android apps, but on linux I'd blame writing to uninitialized pipe resulting in dropping the text, thus not executing the command. My phone is quite slow - Nexus S, CM11.

**Comment by u8sand** [comment]
I get this issue as well, my error log:
*doing this from my phone give me 5 minutes to edit and put in code block.

FINGERPRINT=samsung/d2uc/d2att:4.3/JSS15J/I747UCUEMJB:user/release-keys
HARDWARE=qcom
UNKNOWN=unknown
RADIO=unknown
BOARD=MSM8960
PRODUCT=cm_d2lte
DISPLAY=cm_d2lte-userdebug 4.4.4 KTU84Q 87f9f72608 test-keys
USER=jenkins
HOST=cyanogenmod
DEVICE=d2att
TAGS=test-keys
MODEL=SAMSUNG-SGH-I747
BOOTLOADER=I747UCUFNJ1
CPU_ABI=armeabi-v7a
CPU_ABI2=armeabi
IS_DEBUGGABLE=true
ID=KTU84Q
SERIAL=b912a0b2
MANUFACTURER=samsung
BRAND=samsung
TYPE=userdebug
java.lang.NullPointerException
	at com.hipipal.texteditor.TedActivity.runScript(TedActivity.java:1916)
	at com.hipipal.texteditor.TedActivity.onPlay(TedActivity.java:1906)
	at com.hipipal.texteditor.TedActivity$5.onClick(TedActivity.java:573)
	at android.view.View.performClick(View.java:4445)
	at android.view.View$PerformClick.run(View.java:18446)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5146)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by riverfor** [comment]
u8sand, what version of QPython were you using ?

**Comment by u8sand** [comment]
The latest on Google play (0.9.7); though when I "check for new version" it
says latest (0.9.0).  either way it hasn't been functioning for a while now.

**Comment by vafleite** [comment]
Same here. I tested it with QPython and QPython3 and got the same problem.

Seems that the scripts are not even running at all. As root I changed the script /data/data/com.hipipal.qpyplus/files/bin/qpython.sh to try to debug the problem but nothing happen.

@u8sand how did you get that log? @riverfor do you need any more info?

thanks

**Comment by u8sand** [comment]
It was just there in my /sdcard directory, who knows if it corresponds to
the issue I'm interested in. I had the issue with both QPython and QPython3
as well.

**Comment by vafleite** [comment]
Thanks! I didn't find any log file like this one on mine... :(

**Comment by Gresebc** [comment]
I have found that removing the command 'resize' that is in the mkshrc file solves the problem.

Moto E with CM11.

I'm no speak english.

**Comment by borkins** [comment]
Thank you! 
It really solves this issue.

[ SG Ace 2 with CM11 ]

**Comment by vafleite** [comment]
Thank you @Gresebc! It really worked!!

[GT-i8190 with CM11]

**Comment by ale5000-git** [comment]
Is there is a new version without this problem?

**Comment by SUJAYASNAIR** [comment]
I can't use enter key in qpython
